<script src="assets/js/jquery-1.11.1.min.js"></script>
<!-- <script src="assets/js/jquery-3.3.1.slim.min.js"></script> -->
<script src="assets/js/popper.js"></script>
<script src="assets/js/bootstrap.min.js"></script>
<script src="assets/js/jquery.touchSwipe.min.js"></script>
<script src="assets/js/owl.carousel.min.js"></script>
<script src="assets/js/scroll-bar.js"></script>
<script src="assets/js/jquery.fancybox.min.js"></script>
<script src="assets/js/wow.js"></script>
<script src="assets/js/custom.js"></script>	